---
title: "Taxonomy"
author: "Haydeé"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE}
library("phyloseq")
library("ggplot2")
library("RColorBrewer")
library("patchwork")
library("readr")
library("tidyverse")
library("grid")
library("gridExtra")
library("paletteer")
library("forcats")
library(plyr)
library(reshape2)
library(vegan)
library(here)
```

First, we need to read the biom files. In this file, we found the following **Kingdoms**.

```{r, echo=FALSE}
# ruta
ruta <- here::here("data/bioms", "honey_4_20_Es_Shotgun_Mexico_json.biom")

# read the biom file
raw_metagenomes <- import_biom(as.character(here::here("data/bioms", "honey_4_20_Es_Shotgun_Mexico_json.biom")))

# short the names, quit the first 4 characteres
raw_metagenomes@tax_table@.Data <- substring(raw_metagenomes@tax_table@.Data, 4)
#View(raw_metagenomes@tax_table@.Data)

# rename the columns
colnames(raw_metagenomes@tax_table@.Data)<- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")
#View(raw_metagenomes@tax_table@.Data)

# Obtener los nombres de las muestras
sample_names <- sample_names(raw_metagenomes)

# Cambiar nombres con "_Meli" a "Meli_número"
sample_names <- gsub("(\\d+)_Melli", "Meli_\\1", sample_names)

# Cambiar nombres con "_Scapto" a "Scapto_número"
sample_names <- gsub("(\\d+)_Scapto", "Scapto_\\1", sample_names)

# Asignar los nuevos nombres de las muestras al objeto phyloseq
sample_names(raw_metagenomes) <- sample_names

# upload the metadata
df_meta <- read_csv(here::here("data/tables","metadata_Es_Shotgun_Mex_up.csv"))

df_meta <- df_meta %>%
  mutate(sample_name = sub("Melli", "Meli", sample_name))


# rename the names for the Mex samples
# change n_specie to specie_n
df_meta <- df_meta %>%
  mutate(sample_name = case_when(
    grepl("_Meli", sample_name) ~ paste0("Meli_", sub("_Meli.*", "", sample_name)),
    grepl("_Scapto", sample_name) ~ paste0("Scapto_", sub("_Scapto.*", "", sample_name)),
    TRUE ~ sample_name
  ))


# Asegúrate de que los rownames están bien definidos
rownames(df_meta) <- df_meta$sample_name

# Reordenar según el orden de sample_names en el objeto phyloseq
df_meta_ordenado <- df_meta[match(sample_names(raw_metagenomes), df_meta$sample_name), ]


# change the metadata name of samples to construct a new biom file
df_metadata <- sample_data(df_meta_ordenado)
rownames(df_metadata) <- df_meta_ordenado$sample_name

# construc the new biom file with the new names of the samples
all_data <- merge_phyloseq(raw_metagenomes, sample_data(df_metadata))

# Verificar los nuevos nombres de las muestras
sample_names(all_data)
```
```{r}
muestras_vacias <- sample_names(all_data)[sample_sums(all_data) < 20000]
print(muestras_vacias)
data_filt <- prune_samples(sample_sums(all_data) >= 20000, all_data)
```


```{r, eval=FALSE}
saveRDS(data_filt, file = here::here("data/bioms", "honey_Es_Shotgun_Mexico_filter.rds"))
```

```{r}
all_data <- data_filt
```

## Alpha diversity

```{r}
data <- subset_taxa(all_data, Kingdom == "Bacteria")
alpha_plot <- plot_richness(physeq = data, color= "Specie",
                                measures = c("Observed", "Shannon"))+
  geom_point(shape = 15, size = 3) +
  facet_grid(~Specie)+
  scale_color_manual(values = c("#009292", "#FF6DB6", "#006DDB", "#B66DFF", "#924900", "#DB6D00"))+
  labs(x= "Samples")+
  theme(
    text = element_text(size = 16), # Cambia el tipo de letra y tamaño
    plot.title = element_text(size = 16, face = "bold"), # Tamaño y estilo del título
    axis.title.x = element_text(size = 14, face = "bold"), # Tamaño y estilo del título del eje X
    axis.title.y = element_text(size = 14, face = "bold"), # Tamaño y estilo del título del eje Y
    axis.text.x = element_text(size = 12), # Tamaño de las etiquetas del eje X
    axis.text.y = element_text(size = 12), # Tamaño de las etiquetas del eje Y
    legend.title = element_text(size = 14, face = "bold"), # Tamaño y estilo del título de la leyenda
    legend.text = element_text(size = 14), # Tamaño del texto de la leyenda
    legend.position = "bottom"
  )
alpha_plot
```



```{r}
all_colors <- paletteer::paletteer_d("colorBlindness::SteppedSequential5Steps")
color_matrix <- matrix(all_colors, nrow = 5, byrow = TRUE)
data <- subset_taxa(all_data, Kingdom == "Viruses") #Eukaryota, Viruses, Archaea
# Obtener categorías únicas de la variable (ej. Specie, Country, City)
categorias <- unique(sample_data(data)$Specie)
categorias <- na.omit(categorias)
n_cat <- length(categorias)

# Colores fijos para algunas categorías
colores_fijos <- c(
  "Melipona beecheii" = "#b8860b",
  "Scaptotrigona mexicana" = "#FFBF00"
)


# Separar las categorías que tienen color fijo
categorias_fijas <- intersect(categorias, names(colores_fijos))
categorias_restantes <- setdiff(categorias, categorias_fijas)
n_restantes <- length(categorias_restantes)

# Seleccionar colores para las restantes
if (n_restantes <= 5) {
  selected <- t(color_matrix)[1, 1:n_restantes]
  
} else if (n_restantes <= 10) {
  tonos <- c(1, 3)
  color_combos <- as.vector((color_matrix)[, tonos + 2])
  selected <- color_combos[1:n_restantes]
  
} else if (n_restantes <= 25) {
  selected <- t(all_colors)[1:n_restantes]
  
} else {
  selected <- rep(t(all_colors), length.out = n_restantes)
}

# Asignar nombres
names(selected) <- categorias_restantes

# Combinar con los colores fijos
selected_colors <- c(colores_fijos[categorias_fijas], selected)


alpha_plot <- plot_richness(physeq = data, x= "Specie",
                                measures = c("Observed"))+ #c("Observed", "Chao1", "ACE", "Shannon", "Simpson", "InvSimpson", "Fisher")
  geom_boxplot(aes(fill = Specie), show.legend = FALSE) +
  geom_jitter(aes(), height = 0, width = .1) +
  scale_fill_manual(values = selected_colors) +
  #scale_color_manual(values = c("#009292", "#FF6DB6", "#006DDB", "#B66DFF", "#924900", "#DB6D00"))+
  labs(x= "Samples")+
  theme(
    text = element_text(size = 16), # Cambia el tipo de letra y tamaño
    plot.title = element_text(size = 16, face = "bold"), # Tamaño y estilo del título
    axis.title.x = element_text(size = 14, face = "bold"), # Tamaño y estilo del título del eje X
    axis.title.y = element_text(size = 14, face = "bold"), # Tamaño y estilo del título del eje Y
    axis.text.x = element_text(size = 12), # Tamaño de las etiquetas del eje X
    axis.text.y = element_text(size = 12), # Tamaño de las etiquetas del eje Y
    legend.title = element_text(size = 14, face = "bold"), # Tamaño y estilo del título de la leyenda
    legend.text = element_text(size = 14), # Tamaño del texto de la leyenda
    legend.position = "bottom"
  )
alpha_plot
```

```{r}
alphadiv <- estimate_richness(data, measures = c("Observed", "Chao1", "Shannon", "Simpson")) %>%
  rownames_to_column(var = "sample_name") %>%
  left_join(as.data.frame(sample_data(data)), by = "sample_name") 
```


```{r}
kruskal.test(Observed ~ Country, data = alphadiv) 
```
```{r}
library(FSA)
dunnO <- dunnTest(Observed ~ Specie,
                  data=alphadiv,
                  method="bh")
dunnO
```

## Beta diversity

```{r}
meta_ord <- ordinate(physeq = data, method = "NMDS", 
                     distance = "bray")

beta_div_plot <- plot_ordination(physeq = data, ordination = meta_ord, color="Country", shape="Specie") +
  geom_point(size = 4) +  # Adjust point size
  #scale_color_manual(values = c("#009292", "#FF6DB6", "#006DDB", "#B66DFF", "#924900", "#DB6D00"))+
  theme_minimal() +  # Use a minimal theme for clean look
  theme(legend.position = "right") +  # Position legend on the right
  labs(x = "NMDS1", y = "NMDS2")+
  theme(
    text = element_text(size = 16), # Cambia el tipo de letra y tamaño
    plot.title = element_text(size = 16, face = "bold"), # Tamaño y estilo del título
    axis.title.x = element_text(size = 14, face = "bold"), # Tamaño y estilo del título del eje X
    axis.title.y = element_text(size = 14, face = "bold"), # Tamaño y estilo del título del eje Y
    axis.text.x = element_text(size = 12), # Tamaño de las etiquetas del eje X
    axis.text.y = element_text(size = 12), # Tamaño de las etiquetas del eje Y
    legend.title = element_text(size = 14, face = "bold"), # Tamaño y estilo del título de la leyenda
    legend.text = element_text(size = 14, face = "italic") # Tamaño del texto de la leyenda
  )+
  guides(
    color = guide_legend(override.aes = list(shape = 15))
  )
beta_div_plot
```

```{r}
rel_data <- transform_sample_counts(data, function(x) x*100 / sum(x) )
```

```{r}
# method = NMDS, PCoA, 
meta_ord <- ordinate(physeq = rel_data, method = "NMDS", 
                     distance = "bray")

beta_div_plot <- plot_ordination(physeq = rel_data, ordination = meta_ord, color="Country", shape="Specie") +
  geom_point(size = 4) +  # Adjust point size
  #scale_color_manual(values = c("#009292", "#FF6DB6", "#006DDB", "#B66DFF", "#924900", "#DB6D00"))+
  theme_minimal() +  # Use a minimal theme for clean look
  theme(legend.position = "right") +  # Position legend on the right
  #labs(x = "NMDS1", y = "NMDS2")+
  theme(
    text = element_text(size = 16), # Cambia el tipo de letra y tamaño
    plot.title = element_text(size = 16, face = "bold"), # Tamaño y estilo del título
    axis.title.x = element_text(size = 14, face = "bold"), # Tamaño y estilo del título del eje X
    axis.title.y = element_text(size = 14, face = "bold"), # Tamaño y estilo del título del eje Y
    axis.text.x = element_text(size = 12), # Tamaño de las etiquetas del eje X
    axis.text.y = element_text(size = 12), # Tamaño de las etiquetas del eje Y
    legend.title = element_text(size = 14, face = "bold"), # Tamaño y estilo del título de la leyenda
    legend.text = element_text(size = 14, face = "italic") # Tamaño del texto de la leyenda
  )+
  guides(
    color = guide_legend(override.aes = list(shape = 15))
  )
beta_div_plot
```


```{r}
data <- subset_taxa(all_data, Kingdom == "Bacteria") #Eukaryota, Viruses, Archaea
data_subset <- subset_taxa(data, Genus != "")
rel_data <- transform_sample_counts(data_subset, function(x) x*100 / sum(x) )
# method = NMDS, PCoA, 
meta_ord <- ordinate(physeq = rel_data, method = "NMDS", 
                     distance = "bray")

beta_div_plot <- plot_ordination(physeq = rel_data, ordination = meta_ord, color="Country", shape="Specie") +
  geom_point(size = 4) +  # Adjust point size
  #scale_color_manual(values = c("#009292", "#FF6DB6", "#006DDB", "#B66DFF", "#924900", "#DB6D00"))+
  theme_minimal() +  # Use a minimal theme for clean look
  theme(legend.position = "right") +  # Position legend on the right
  #labs(x = "NMDS1", y = "NMDS2")+
  theme(
    text = element_text(size = 16), # Cambia el tipo de letra y tamaño
    plot.title = element_text(size = 16, face = "bold"), # Tamaño y estilo del título
    axis.title.x = element_text(size = 14, face = "bold"), # Tamaño y estilo del título del eje X
    axis.title.y = element_text(size = 14, face = "bold"), # Tamaño y estilo del título del eje Y
    axis.text.x = element_text(size = 12), # Tamaño de las etiquetas del eje X
    axis.text.y = element_text(size = 12), # Tamaño de las etiquetas del eje Y
    legend.title = element_text(size = 14, face = "bold"), # Tamaño y estilo del título de la leyenda
    legend.text = element_text(size = 14, face = "italic") # Tamaño del texto de la leyenda
  )+
  guides(
    color = guide_legend(override.aes = list(shape = 15))
  )
beta_div_plot
```


```{r}
set.seed(1234)
bray_dist <- distance(data, method = "bray")
metadata <- sample_data(data)

metadata <- as.data.frame(metadata)

adonis2(bray_dist ~ metadata$Specie)

adonis2(bray_dist ~ metadata$Country, permutations = 1000)

```

## Diversidad

```{r}
# Agrupar por Kingdom
rel_phylum_global <- tax_glom(all_data, taxrank = 'Kingdom')

# Transformar los datos a porcentajes por muestra
rel_phylum_global <- transform_sample_counts(rel_phylum_global, function(x) x * 100 / sum(x))

# Convertir a data.frame para visualización y análisis
rel_phyl_global_df <- psmelt(rel_phylum_global)

# Convertir la columna 'Kingdom' en factor
rel_phyl_global_df$Kingdom <- as.factor(rel_phyl_global_df$Kingdom)
```

```{r}
# Define your custom color palette
phylum_colors_rel <- c(
  "Bacteria" = "#4F81BD", ##1f78b4", 
  "Eukaryota" = "#9BBB59"  , #"#33a02c",
  "Viruses" = "#F79646",#"#6a3d9a"
  "Archaea" = "red"
)

rel_phyl_global_df$Kingdom <- factor(rel_phyl_global_df$Kingdom, levels = c("Archaea", "Bacteria", "Eukaryota", "Viruses"))

relative_plot_phylum <- ggplot(data=rel_phyl_global_df, aes(x=Sample, y=Abundance, fill=Kingdom))+ 
  geom_bar(aes(), stat="identity", position="stack")+
  scale_fill_manual(values = phylum_colors_rel)+
  labs(x= "Samples", y = "Relative abundance") +
  theme( legend.text = element_text(size = 16, face = "italic"), 
         legend.key.size = unit(0.4, 'cm'), 
         axis.title = element_text(size = 16), 
         axis.text.x = element_text(size = 16, angle = 90),
         axis.text.y = element_text(size = 16), 
         plot.title = element_text(size = 20), 
         axis.title.x = element_text(size = 16, face = "bold"),
         axis.title.y = element_text(size = 16, face = "bold"), 
         legend.title = element_text(size = 16),
         legend.position = "bottom")


relative_plot_phylum
```


```{r}
data <- subset_taxa(all_data, Kingdom == "Bacteria") #Eukaryota, Viruses, Archaea
data <- subset_taxa(data, Genus != "")
#Subset
rel_phylum_global <- tax_glom(data, taxrank = 'Phylum')
rel_phylum_global <- transform_sample_counts(rel_phylum_global, function(x) x*100 / sum(x) )
rel_phyl_global_df<-psmelt(rel_phylum_global) # convert to data frame
#str(rel_phyl_global_df)
rel_phyl_global_df$Phylum[rel_phyl_global_df$Abundance < 5] <- "Phyla < 5% abund"
rel_phyl_global_df$Phylum <- as.factor(rel_phyl_global_df$Phylum)
```


```{r, echo=FALSE}

all_colors <- paletteer::paletteer_d("colorBlindness::SteppedSequential5Steps")
color_matrix <- matrix(all_colors, nrow = 5, byrow = TRUE)
#data <- subset_taxa(all_data, Kingdom == "Viruses") #Eukaryota, Viruses, Archaea
# Obtener categorías únicas de la variable (ej. Specie, Country, City)
categorias <- unique(rel_phyl_global_df$Phylum)
n_cat <- length(categorias)

# Separar las categorías que tienen color fijo
# Seleccionar colores para las restantes
if (n_cat <= 5) {
  selected <- t(color_matrix)[1, 1:n_cat]
  
} else if (n_cat <= 10) {
  tonos <- c(1, 3)
  color_combos <- as.vector((color_matrix)[, tonos + 2])
  selected <- color_combos[1:n_cat]
  
} else if (n_cat <= 25) {
  selected <- t(all_colors)[1:n_cat]
  
} else {
  selected <- rep(t(all_colors), length.out = n_cat)
}

# Asignar nombres
names(selected) <- categorias




relative_plot_phylum <- ggplot(data=rel_phyl_global_df, aes(x=Sample, y=Abundance, fill=Phylum))+ 
  geom_bar(aes(), stat="identity", position="stack")+
  #scale_fill_paletteer_d("colorBlindness::PairedColor12Steps")
  scale_fill_manual(values = selected)+
  labs(x= "Samples", y = "Relative abundance") +
  theme( legend.text = element_text(size = 16, face = "italic"), 
         legend.key.size = unit(0.4, 'cm'), 
         axis.title = element_text(size = 16), 
         axis.text.x = element_text(size = 16, angle = 90),
         axis.text.y = element_text(size = 16), 
         plot.title = element_text(size = 20), 
         axis.title.x = element_text(size = 16, face = "bold"),
         axis.title.y = element_text(size = 16, face = "bold"), 
         legend.title = element_text(size = 16),
         legend.position = "bottom")


relative_plot_phylum
```